var identityServerDb = db.getSiblingDB('TS_IdentityServer');
var collection = identityServerDb.getCollection("Clients");

if (collection.countDocuments({}) === 0) {
  collection.insertMany(
    [
      {
        "Enabled": true,
        "ClientId": "web",
        "ProtocolType": "oidc",
        "ClientSecrets": [{
          "Description": null,
          "Value": "SO2EXXgXBs8YdkSxYS8JjLvBAQXNYrZkQCATnnyLPD4=",//cafd9713-c6c5-4096-a29d-02988424942b
          "Expiration": null,
          "Type": "SharedSecret",
          "Created": new Date()
        }],
        "RequireClientSecret": false,
        "ClientName": null,
        "Description": null,
        "ClientUri": null,
        "LogoUri": null,
        "RequireConsent": false,
        "AllowRememberConsent": true,
        "AlwaysIncludeUserClaimsInIdToken": true,
        "AllowedGrantTypes": [
          "authorization_code"
        ],
        "RequirePkce": true,
        "AllowPlainTextPkce": false,
        "RequireRequestObject": false,
        "AllowAccessTokensViaBrowser": true,
        "RedirectUris": [
          "http://localhost:8080",
          "http://localhost:3000"
        ],
        "PostLogoutRedirectUris": [
          "http://localhost:8080",
          "http://localhost:3000"
        ],
        "FrontChannelLogoutUri": null,
        "FrontChannelLogoutSessionRequired": true,
        "BackChannelLogoutUri": null,
        "BackChannelLogoutSessionRequired": true,
        "AllowOfflineAccess": true,
        "AllowedScopes": [
          "treatment",
          "openid"
        ],
        "IdentityTokenLifetime": 300,
        "AllowedIdentityTokenSigningAlgorithms": [],
        "AccessTokenLifetime": 3600,
        "AuthorizationCodeLifetime": 300,
        "AbsoluteRefreshTokenLifetime": 2592000,
        "SlidingRefreshTokenLifetime": 1296000,
        "ConsentLifetime": null,
        "RefreshTokenUsage": 1,
        "UpdateAccessTokenClaimsOnRefresh": false,
        "RefreshTokenExpiration": 1,
        "AccessTokenType": 0,
        "EnableLocalLogin": true,
        "IdentityProviderRestrictions": [],
        "IncludeJwtId": true,
        "Claims": [],
        "AlwaysSendClientClaims": true,
        "ClientClaimsPrefix": "client_",
        "PairWiseSubjectSalt": null,
        "UserSsoLifetime": null,
        "UserCodeType": null,
        "DeviceCodeLifetime": 300,
        "AllowedCorsOrigins": [],
        "Properties": [],
        "Created": new Date(),
        "Updated": null,
        "LastAccessed": null
      },
      {
        "_id": ObjectId("61e1ab64c9662a8a72d52a35"),
        "Enabled": true,
        "ClientId": "mobile_android",
        "ProtocolType": "oidc",
        "ClientSecrets": [{
          "Description": null,
          "Value": "GkX++b2JqTA0ZXC0KnbByxuC8wj55MGiWQFGyEeezjQ=",//ace5cdae-952b-479c-baec-575acf58d866
          "Expiration": null,
          "Type": "SharedSecret",
          "Created": new Date(),
        }],
        "RequireClientSecret": true,
        "ClientName": "mobile_android",
        "Description": null,
        "ClientUri": null,
        "LogoUri": null,
        "RequireConsent": false,
        "AllowRememberConsent": true,
        "AlwaysIncludeUserClaimsInIdToken": false,
        "AllowedGrantTypes": [
          "password"
        ],
        "RequirePkce": false,
        "AllowPlainTextPkce": false,
        "RequireRequestObject": false,
        "AllowAccessTokensViaBrowser": false,
        "RedirectUris": [],
        "PostLogoutRedirectUris": [],
        "FrontChannelLogoutUri": null,
        "FrontChannelLogoutSessionRequired": true,
        "BackChannelLogoutUri": null,
        "BackChannelLogoutSessionRequired": true,
        "AllowOfflineAccess": true,
        "AllowedScopes": [
          "treatment",
          "identity",
          "openid"
        ],
        "IdentityTokenLifetime": 300,
        "AllowedIdentityTokenSigningAlgorithms": [],
        "AccessTokenLifetime": 3600,
        "AuthorizationCodeLifetime": 300,
        "AbsoluteRefreshTokenLifetime": 2592000,
        "SlidingRefreshTokenLifetime": 1296000,
        "ConsentLifetime": null,
        "RefreshTokenUsage": 1,
        "UpdateAccessTokenClaimsOnRefresh": false,
        "RefreshTokenExpiration": 0,
        "AccessTokenType": 0,
        "EnableLocalLogin": true,
        "IdentityProviderRestrictions": [],
        "IncludeJwtId": true,
        "Claims": [],
        "AlwaysSendClientClaims": true,
        "ClientClaimsPrefix": "client_",
        "PairWiseSubjectSalt": null,
        "UserSsoLifetime": null,
        "UserCodeType": null,
        "DeviceCodeLifetime": 300,
        "AllowedCorsOrigins": [],
        "Properties": [],
        "Created": new Date(),
        "Updated": null,
        "LastAccessed": null
      },
      {
        "_id": ObjectId("61e1ab64c9662a8a72d52a34"),
        "Enabled": true,
        "ClientId": "mobile_ios_anonymous",
        "ProtocolType": "oidc",
        "ClientSecrets": [{
          "Description": null,
          "Value": "GXEhgCSjhccD/sN+OFR71eZAb1seBqduVaNjgrOy4jI=",//164f3a38-1500-4f00-9046-3c2298e7f356
          "Expiration": null,
          "Type": "SharedSecret",
          "Created": new Date(),
        }],
        "RequireClientSecret": true,
        "ClientName": "mobile_ios_anonymous",
        "Description": null,
        "ClientUri": null,
        "LogoUri": null,
        "RequireConsent": false,
        "AllowRememberConsent": true,
        "AlwaysIncludeUserClaimsInIdToken": false,
        "AllowedGrantTypes": [
          "client_credentials"
        ],
        "RequirePkce": false,
        "AllowPlainTextPkce": false,
        "RequireRequestObject": false,
        "AllowAccessTokensViaBrowser": false,
        "RedirectUris": [],
        "PostLogoutRedirectUris": [],
        "FrontChannelLogoutUri": null,
        "FrontChannelLogoutSessionRequired": true,
        "BackChannelLogoutUri": null,
        "BackChannelLogoutSessionRequired": true,
        "AllowOfflineAccess": false,
        "AllowedScopes": [
          "identity"
        ],
        "IdentityTokenLifetime": 300,
        "AllowedIdentityTokenSigningAlgorithms": [],
        "AccessTokenLifetime": 7776000,
        "AuthorizationCodeLifetime": 300,
        "AbsoluteRefreshTokenLifetime": 2592000,
        "SlidingRefreshTokenLifetime": 1296000,
        "ConsentLifetime": null,
        "RefreshTokenUsage": 1,
        "UpdateAccessTokenClaimsOnRefresh": false,
        "RefreshTokenExpiration": 0,
        "AccessTokenType": 0,
        "EnableLocalLogin": true,
        "IdentityProviderRestrictions": [],
        "IncludeJwtId": true,
        "Claims": [],
        "AlwaysSendClientClaims": false,
        "ClientClaimsPrefix": "client_",
        "PairWiseSubjectSalt": null,
        "UserSsoLifetime": null,
        "UserCodeType": null,
        "DeviceCodeLifetime": 300,
        "AllowedCorsOrigins": [],
        "Properties": [],
        "Created": ISODate("2022-01-14T16:57:08.016Z"),
        "Updated": null,
        "LastAccessed": null
      }, {
        "_id": ObjectId("61e1ab64c9662a8a72d52a36"),
        "Enabled": true,
        "ClientId": "mobile_android_anonymous",
        "ProtocolType": "oidc",
        "ClientSecrets": [{
          "Description": null,
          "Value": "hu/ZGsJmltMZYVOpoOZqVFFbBtsfe33VhfCZQYVwmdY=",//15834b5b-0b1d-498c-b6bd-e78cbbf70bac
          "Expiration": null,
          "Type": "SharedSecret",
          "Created": new Date(),
        }],
        "RequireClientSecret": true,
        "ClientName": "mobile_android_anonymous",
        "Description": null,
        "ClientUri": null,
        "LogoUri": null,
        "RequireConsent": false,
        "AllowRememberConsent": true,
        "AlwaysIncludeUserClaimsInIdToken": false,
        "AllowedGrantTypes": [
          "client_credentials"
        ],
        "RequirePkce": false,
        "AllowPlainTextPkce": false,
        "RequireRequestObject": false,
        "AllowAccessTokensViaBrowser": false,
        "RedirectUris": [],
        "PostLogoutRedirectUris": [],
        "FrontChannelLogoutUri": null,
        "FrontChannelLogoutSessionRequired": true,
        "BackChannelLogoutUri": null,
        "BackChannelLogoutSessionRequired": true,
        "AllowOfflineAccess": false,
        "AllowedScopes": [
          "identity"
        ],
        "IdentityTokenLifetime": 300,
        "AllowedIdentityTokenSigningAlgorithms": [],
        "AccessTokenLifetime": 7776000,
        "AuthorizationCodeLifetime": 300,
        "AbsoluteRefreshTokenLifetime": 2592000,
        "SlidingRefreshTokenLifetime": 1296000,
        "ConsentLifetime": null,
        "RefreshTokenUsage": 1,
        "UpdateAccessTokenClaimsOnRefresh": false,
        "RefreshTokenExpiration": 0,
        "AccessTokenType": 0,
        "EnableLocalLogin": true,
        "IdentityProviderRestrictions": [],
        "IncludeJwtId": true,
        "Claims": [],
        "AlwaysSendClientClaims": false,
        "ClientClaimsPrefix": "client_",
        "PairWiseSubjectSalt": null,
        "UserSsoLifetime": null,
        "UserCodeType": null,
        "DeviceCodeLifetime": 300,
        "AllowedCorsOrigins": [],
        "Properties": [],
        "Created": ISODate("2022-01-14T16:57:08.016Z"),
        "Updated": null,
        "LastAccessed": null
      }, {
        "Enabled": true,
        "ClientId": "mobile_ios",
        "ProtocolType": "oidc",
        "ClientSecrets": [{
          "Description": null,
          "Value": "Qj0g99tQyzQ1TvQ9vIQ8s9E9ldZxuUgW1dFb6eML2XI=",//753b420c-5ff3-4e52-b902-13369b0e4fa1
          "Expiration": null,
          "Type": "SharedSecret",
          "Created": new Date(),
        }],
        "RequireClientSecret": true,
        "ClientName": "mobile_ios",
        "Description": null,
        "ClientUri": null,
        "LogoUri": null,
        "RequireConsent": false,
        "AllowRememberConsent": true,
        "AlwaysIncludeUserClaimsInIdToken": false,
        "AllowedGrantTypes": [
          "password"
        ],
        "RequirePkce": false,
        "AllowPlainTextPkce": false,
        "RequireRequestObject": false,
        "AllowAccessTokensViaBrowser": false,
        "RedirectUris": [],
        "PostLogoutRedirectUris": [],
        "FrontChannelLogoutUri": null,
        "FrontChannelLogoutSessionRequired": true,
        "BackChannelLogoutUri": null,
        "BackChannelLogoutSessionRequired": true,
        "AllowOfflineAccess": true,
        "AllowedScopes": [
          "treatment",
          "identity",
          "openid"
        ],
        "IdentityTokenLifetime": 300,
        "AllowedIdentityTokenSigningAlgorithms": [],
        "AccessTokenLifetime": 3600,
        "AuthorizationCodeLifetime": 300,
        "AbsoluteRefreshTokenLifetime": 2592000,
        "SlidingRefreshTokenLifetime": 1296000,
        "ConsentLifetime": null,
        "RefreshTokenUsage": 1,
        "UpdateAccessTokenClaimsOnRefresh": false,
        "RefreshTokenExpiration": 0,
        "AccessTokenType": 0,
        "EnableLocalLogin": true,
        "IdentityProviderRestrictions": [],
        "IncludeJwtId": true,
        "Claims": [],
        "AlwaysSendClientClaims": false,
        "ClientClaimsPrefix": "client_",
        "PairWiseSubjectSalt": null,
        "UserSsoLifetime": null,
        "UserCodeType": null,
        "DeviceCodeLifetime": 300,
        "AllowedCorsOrigins": [],
        "Properties": [],
        "Created": new Date(),
        "Updated": null,
        "LastAccessed": null
      }
    ]
  );
}